const assert = require('node:assert/strict');
const { spawn } = require('node:child_process');
const http = require('node:http');
const path = require('node:path');
const fs = require('node:fs');
const os = require('node:os');
let chromium;
try { ({ chromium } = require('playwright')); } catch {}

function getJson(port, pathname) {
  return new Promise((resolve, reject) => {
    const request = http.get(`http://127.0.0.1:${port}${pathname}`, response => {
      let body = ''; response.setEncoding('utf8'); response.on('data', chunk => { body += chunk; });
      response.on('end', () => response.statusCode === 200 ? resolve(JSON.parse(body)) : reject(new Error(body)));
    });
    request.on('error', reject);
  });
}

async function waitForServer(port) {
  for (let attempt = 0; attempt < 600; attempt++) {
    try { return await getJson(port, '/api/state'); } catch { await new Promise(resolve => setTimeout(resolve, 100)); }
  }
  throw new Error('backend did not start');
}

(async () => {
  const root = path.resolve(__dirname, '..');
  const port = Number(process.env.METHODATLAS_CHECK_PORT || process.env.METHODATLAS_UI_PORT || 8799);
  const testData = fs.mkdtempSync(path.join(os.tmpdir(), 'methodatlas-ui-'));
  const server = spawn(process.env.PYTHON || 'python', ['-m', 'backend.app', '--port', String(port), '--data-dir', testData, '--pdf-dir', path.join(root, 'missing-papers')], {cwd: root, stdio: 'ignore', windowsHide: true, env: {...process.env, DEEPSEEK_API_KEY: ''}});
  server.unref();
  process.on('exit', () => server.kill());
  const state = await waitForServer(port).catch(error => { server.kill(); throw error; });
  if (!chromium) {
    assert.equal(state.projects.length, 1);
    assert.equal(state.projects[0].papers.length, 0);
    console.log('PASS: backend API shell and empty local material state (Playwright not installed; UI check skipped).');
    server.kill();
    return;
  }
  const browser = await chromium.launch({...process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE ? {executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE} : {channel:'chromium'}, headless: true});
  try {
    const page = await browser.newPage();
    page.setDefaultTimeout(30000);
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    const screenshots = path.join(root,'.methodatlas-data','ui-check');
    fs.mkdirSync(screenshots,{recursive:true});
    let submittedMessages = 0;
    page.on('request', request => { if (request.method() === 'POST' && request.url().endsWith('/messages')) { submittedMessages++; assert.equal(request.postDataJSON().replace_active,true); } });
    let taskRequestResolve;
    const taskRequestStarted = new Promise(resolve => { taskRequestResolve = resolve; });
    await page.route('**/api/projects/*', async route => {
      if (submittedMessages) {
        taskRequestResolve();
        await new Promise(resolve => setTimeout(resolve, 300));
      }
      await route.continue();
    });
    await page.goto(`http://127.0.0.1:${port}/`, {waitUntil: 'networkidle'});
    await page.locator('.home .brand').waitFor();
    assert.equal(await page.locator('.project-card').count(), 2);
    assert.equal(await page.locator('.project-card').first().getByText('新建项目').count(), 1);
    await page.getByRole('button',{name:'设置',exact:true}).click();
    await page.getByRole('button',{name:'研究与工作区',exact:true}).click();
    await page.locator('#settings-view').selectOption('list');
    assert.equal(await page.locator('.projects.list-view').count(),1);
    await page.locator('#settings-view').selectOption('grid');
    await page.getByRole('button',{name:'关闭设置',exact:true}).click();
    for (const [url,type] of [['/home.css','text/css'],['/assets/methodatlas-mark.png','image/png'],['/vendor/pdfjs/pdf.min.mjs','text/javascript'],['/vendor/pdfjs/pdf.worker.min.mjs','text/javascript']]) {
      const response = await page.request.get(`http://127.0.0.1:${port}${url}`);
      assert.equal(response.status(),200);
      assert.ok(response.headers()['content-type'].startsWith(type));
    }
    assert.equal((await page.request.get(`http://127.0.0.1:${port}/assets/AGENTS.md`)).status(),404);
    await page.locator('.nb-new').click();
    await page.locator('#project-name').fill('   ');
    await page.getByRole('button',{name:'创建项目',exact:true}).click();
    assert.match(await page.locator('#project-error').textContent(), /请输入/);
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('dialog[open]').count(),0);
    const newNames = ['Zeta 界面集成 <研究>','Alpha 界面集成'];
    for (const name of newNames) {
      await page.locator('.nb-new').click();
      await page.locator('#project-name').fill(name);
      await page.getByRole('button',{name:'创建项目',exact:true}).click();
      await page.locator('.project-title').filter({hasText:name}).waitFor();
      await page.locator('[data-action=home]').click();
      await page.locator('.nb-card h2').getByText(name,{exact:true}).waitFor();
    }
    assert.equal((await getJson(port,'/api/state')).projects.length,3);
    assert.equal(await page.locator('.nb-card h2 img').count(),0);
    await page.locator('#project-search').fill('不存在的关键词');
    await page.locator('.no-project').waitFor();
    assert.equal(await page.locator('.nb-card').count(),0);
    await page.locator('#project-search').fill('界面集成');
    await page.locator('#project-sort').selectOption('name');
    assert.deepEqual(await page.locator('.nb-card h2').allTextContents(),[...newNames].reverse());
    await page.getByRole('button',{name:'列表视图',exact:true}).click();
    assert.equal(await page.locator('.projects.list-view').count(),1);
    await page.reload();
    await page.locator('.projects.list-view').waitFor();
    assert.equal(await page.locator('#project-sort').inputValue(),'name');
    await page.locator('#project-sort').selectOption('recent');
    assert.deepEqual((await page.locator('.nb-card h2').allTextContents()).slice(0,2),[...newNames].reverse());
    await page.getByRole('button',{name:'网格视图',exact:true}).click();
    await page.screenshot({path:path.join(screenshots,'home-grid.png'),animations:'disabled'});
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true);
    await page.screenshot({path:path.join(screenshots,'home-mobile.png'),fullPage:true,animations:'disabled'});
    await page.getByRole('button',{name:'列表视图',exact:true}).click();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true);
    await page.emulateMedia({reducedMotion:'reduce'});
    await page.locator('.nb-card').first().hover();
    assert.equal(await page.locator('.nb-card').first().evaluate(node => getComputedStyle(node).transform),'none');
    await page.setViewportSize({width:1280,height:800});
    await page.locator(`[data-action=open-project][data-id="${state.projects[0].id}"]`).click();
    await page.locator('.panels').waitFor();
    assert.equal(await page.locator('.panel').count(), 3);
    assert.deepEqual(await page.locator('.panels>.panel>.panel-head h2').allTextContents(),['来源','与 AI 对话','Studio']);
    assert.equal(await page.locator('.workspace-actions [data-action=history]').textContent(),'历史记录');
    assert.equal(await page.locator('.workspace-actions [data-action=new-project]').textContent(),'新建项目');
    assert.equal(await page.locator('#chat-panel [data-action=new-chat]').textContent(),'新对话');
    assert.equal(await page.locator('#source-search').isVisible(),true);
    assert.equal(await page.locator('.source-actions button').count(),1);
    assert.doesNotMatch(await page.locator('.workspace').innerText(),/SOURCES|RESEARCH CHAT|PROJECT OUTPUTS|DeepSeek|本地模式|勾选作为重点/);
    assert.equal(await page.locator('.paper-row').count(), 0);
    assert.equal(await page.locator('#output-body [data-action=task]').count(),0);
    for (const key of ['method','comparison','map','evolution','opportunity','lit-review','experiment-plan','result-to-claim']) {
      await page.locator(`.chip[data-value=${key}]`).click();
      assert.ok((await page.locator('#chat-input').inputValue()).length > 20);
      assert.equal(submittedMessages,0,'choosing a capability must only fill the editable draft');
    }
    await page.getByRole('button',{name:'实验设计',exact:true}).focus();
    await page.keyboard.press('Enter');
    assert.match(await page.locator('#chat-input').inputValue(),/baseline/);
    await page.locator('#chat-input').fill('只讨论实验设计，不生成文件。');
    assert.equal(submittedMessages,0);
    assert.equal(await page.locator('[data-action=report-materials],.chip[data-value=figure],.chip[data-value=meeting]').count(),0);
    await page.getByRole('button',{name:'管理 / 保存方法'}).click();
    await page.getByText('从已完成协作提炼 / 复制内置能力',{exact:true}).click();
    await page.getByRole('button',{name:'复制后定制'}).click();
    await page.getByRole('textbox',{name:'名称',exact:true}).fill('个人比较 <方法>');
    await page.reload();
    await page.getByRole('button',{name:'管理 / 保存方法'}).click();
    assert.equal(await page.getByRole('textbox',{name:'名称',exact:true}).inputValue(),'个人比较 <方法>');
    await page.getByRole('button',{name:'确认保存',exact:true}).click();
    await page.locator('#skill-error').filter({hasText:'请预览'}).waitFor();
    await page.locator('#skill-confirm').check();
    await page.getByRole('button',{name:'确认保存',exact:true}).click();
    await page.getByRole('button',{name:'明确更新方法'}).waitFor();
    await page.getByRole('textbox',{name:'步骤',exact:true}).fill('先核对新主题证据，再比较局限。');
    await page.locator('#skill-confirm').check();
    await page.getByRole('button',{name:'明确更新方法'}).click();
    await page.getByText('当前 v2',{exact:false}).waitFor();
    await page.locator('#skill-confirm').check();
    const download = page.waitForEvent('download');
    await page.getByRole('button',{name:'导出 Markdown',exact:true}).click();
    const methodMarkdown = fs.readFileSync(await (await download).path());
    assert.match(methodMarkdown.toString(), /先核对新主题证据/);
    await page.getByRole('button',{name:'生成分享下载地址'}).click();
    const shareLink = await page.getByRole('textbox',{name:'分享下载地址'}).inputValue();
    assert.equal((await page.request.get(shareLink)).status(),200);
    await page.getByRole('button',{name:'撤回分享'}).click();
    await page.locator('#skill-error').filter({hasText:'操作已保存'}).waitFor();
    assert.equal((await page.request.get(shareLink)).status(),400);
    await page.getByRole('button',{name:'关闭我的技能'}).click();
    await page.getByRole('button',{name:'个人比较 <方法>',exact:true}).click();
    assert.match(await page.locator('#chat-input').inputValue(), /skillversion_/);
    assert.equal(submittedMessages,0,'personal method selection must never submit');
    await page.getByRole('button',{name:'管理 / 保存方法'}).click();
    await page.locator('#skill-import').setInputFiles({name:'method.md',mimeType:'text/markdown',buffer:methodMarkdown});
    await page.getByRole('textbox',{name:'名称',exact:true}).filter({visible:true}).waitFor();
    await page.waitForFunction(() => document.querySelector('#skill-name').value === '个人比较 <方法>').catch(async error => {
      error.message += '\nImport status: ' + await page.locator('#skill-error').textContent();
      throw error;
    });
    await page.getByRole('textbox',{name:'名称',exact:true}).fill('导入后定制');
    await page.locator('#skill-confirm').check();
    await page.getByRole('button',{name:'确认保存',exact:true}).click();
    await page.getByRole('button',{name:'明确更新方法'}).waitFor();
    assert.equal(await page.getByRole('textbox',{name:'名称',exact:true}).inputValue(),'导入后定制');
    await page.getByRole('button',{name:'归档',exact:true}).click();
    await page.getByRole('button',{name:'恢复使用'}).waitFor();
    await page.getByRole('button',{name:'关闭我的技能'}).click();
    assert.equal(await page.getByRole('button',{name:'导入后定制',exact:true}).count(),0);
    console.log('PASS: real personal Skill UI confirm/save/edit/export/import/share/revoke/archive; selection only fills the draft.');
    const panelWidths = () => page.locator('.panels>.panel').evaluateAll(nodes => nodes.map(n => n.getBoundingClientRect().width));
    assert.equal(await page.getByRole('separator').count(),2);
    const initialWidths = await panelWidths();
    const handle = await page.getByRole('separator').first().boundingBox();
    await page.mouse.move(handle.x+handle.width/2,handle.y+50);
    await page.mouse.down(); await page.mouse.move(handle.x+handle.width/2+40,handle.y+50); await page.mouse.up();
    assert.ok((await panelWidths())[0] > initialWidths[0]+30);
    assert.equal(await page.locator('body.resizing-panels').count(),0);
    const beforeKeyboard = await panelWidths();
    await page.getByRole('separator').nth(1).press('ArrowLeft');
    assert.ok((await panelWidths())[2] > beforeKeyboard[2]+20);
    const resizedWidths = await panelWidths();
    await page.locator('.chip[data-value=method]').click();
    const shortcutDraft = await page.locator('#chat-input').inputValue();
    assert.match(shortcutDraft,/核心方法/);
    assert.equal(submittedMessages,0,'shortcuts must fill a draft, never submit research');
    await page.reload();
    await page.locator('#chat-input').waitFor();
    assert.equal(await page.locator('#chat-input').inputValue(),shortcutDraft);
    assert.ok((await panelWidths()).every((width,i) => Math.abs(width-resizedWidths[i])<2),'column sizes survive reload');
    assert.equal(await page.locator('#chat-input').evaluate(node => node.getBoundingClientRect().bottom < innerHeight),true);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true);
    await page.screenshot({path:path.join(screenshots,'workspace-welcome.png')});
    const originalView = JSON.parse(await page.evaluate(() => localStorage.getItem('methodatlas-view')));
    await page.locator('.workspace-actions>summary').click();
    await page.locator('.workspace-actions [data-action=new-project]').click();
    await page.locator('#project-name').waitFor();
    await page.keyboard.press('Escape');
    await page.locator('[data-action=new-chat]').click();
    await page.waitForFunction(id => JSON.parse(localStorage.getItem('methodatlas-view')).conversationId !== id,originalView.conversationId);
    assert.equal(await page.locator('#chat-input').inputValue(),'');
    await page.screenshot({path:path.join(screenshots,'workspace-aligned.png'),animations:'disabled'});
    await page.locator('[data-action=history]').click();
    await page.locator('#sources-panel .history-panel').waitFor();
    assert.equal(await page.locator('[data-action=history]').getAttribute('aria-expanded'),'true');
    await page.screenshot({path:path.join(screenshots,'workspace-history.png')});
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#conversation-menu').count(),0);
    assert.equal(await page.locator('[data-action=history]').evaluate(node => node === document.activeElement),true);
    await page.locator('[data-action=history]').click();
    await page.locator(`[data-action=conversation][data-id="${originalView.conversationId}"]`).click();
    await page.waitForFunction(expected => document.getElementById('chat-input')?.value === expected,shortcutDraft);
    await page.getByRole('button', {name:'添加来源',exact:true}).click();
    await page.locator('#text-source-form input[name=title]').fill('展示约定');
    const sourceText = '青色代表感知，紫色代表决策。\n\n1. 第一项\n2. 第二项\n3. 第三项';
    await page.locator('#text-source-form textarea[name=text]').fill(sourceText);
    await page.getByRole('button', {name:'保存文字',exact:true}).click();
    await page.locator('#source-results').getByText('已导入',{exact:true}).waitFor();
    await page.getByRole('button', {name:'返回项目',exact:true}).click();
    await page.locator('.paper-row').waitFor();
    assert.match(await page.locator('.paper-row').innerText(), /展示约定/);
    await page.getByRole('button',{name:'查看论文：展示约定',exact:true}).click();
    assert.equal(await page.locator('.responsive-list').innerText(),'1. 第一项\n2. 第二项\n3. 第三项');
    await page.getByRole('button',{name:'关闭阅读器',exact:true}).click();
    await page.locator('[data-action=home]').click();
    await page.locator(`[data-id="${state.projects[0].id}"]`).getByText(/1 个来源/).waitFor();
    assert.equal(await page.locator('.nb-card').first().getAttribute('data-id'),state.projects[0].id,'recent order should follow the opened project');
    await page.locator(`[data-action=open-project][data-id="${state.projects[0].id}"]`).click();
    await page.locator('#chat-input').waitFor();
    const messageResponse = page.waitForResponse(response => response.url().includes('/messages') && response.request().method() === 'POST');
    await page.locator('#chat-input').fill('测试旧任务不会污染新对话');
    await page.locator('#chat-form').evaluate(form => form.requestSubmit());
    await messageResponse;
    await taskRequestStarted;
    const conversationResponse = page.waitForResponse(response => response.url().includes('/conversations') && response.request().method() === 'POST');
    await page.locator('[data-action=new-chat]').click();
    await conversationResponse;
    await page.waitForTimeout(500);
    assert.equal(await page.locator('.welcome h1').textContent(), '让我们开始梳理这个项目…');
    assert.equal(await page.locator('#chat-input').isDisabled(), false);
    assert.equal(await page.locator('.message.user').count(), 0);
    await page.reload();
    await page.locator('#chat-input').waitFor();
    assert.equal(await page.locator('.paper-row').count(), 1);
    assert.equal(await page.locator('.message.user').count(), 0);
    const saved = await getJson(port, `/api/projects/${state.projects[0].id}`);
    const failed = saved.conversations.flatMap(c => c.messages).find(m => m.task?.status === 'failed');
    assert.match(failed.task.error, /DEEPSEEK_API_KEY/);
    assert.equal(saved.artifacts.length, 0);
    const newDocument = page.waitForResponse(r => r.url().endsWith('/documents') && r.request().method() === 'POST');
    await page.getByRole('button',{name:'新建论文',exact:true}).click();
    const document = await (await newDocument).json();
    await page.getByRole('textbox',{name:'文档标题',exact:true}).fill('当前实验主张文稿');
    const sourceMessage = page.waitForResponse(r => r.url().endsWith('/messages') && r.request().method() === 'POST');
    await page.locator('#chat-input').fill('根据当前文稿讨论实验设计，不修改论文。');
    await page.getByRole('button',{name:'发送任务',exact:true}).click();
    const sourceResponse = await sourceMessage;
    const documentState = await getJson(port, `/api/projects/${saved.id}/documents/${document.artifact_id}`);
    assert.equal(documentState.versions.length,2,'sending research flushes pending edits once');
    assert.deepEqual(sourceResponse.request().postDataJSON().report_sources,[{
      artifact_id:document.artifact_id,version_id:documentState.versions.at(-1).id
    }],'current manuscript version is supplied even without a corresponding chat message');
    assert.equal(documentState.proposals.length,0,'research must not become a manuscript edit proposal');
    const legacy = {id:'legacy', title:'旧版综述', versions:[{id:'legacy-v1', version_no:1, title:'旧版综述', kind:'research', body:'保留的历史正文', payload:{}, materials:[], citations:[], created:'2026-09-01'}]};
    await page.route(`**/api/projects/${saved.id}/artifacts/legacy`, route => route.fulfill({json:legacy}));
    await page.route(`**/api/projects/${saved.id}`, route => route.fulfill({json:{...saved, artifacts:[{id:legacy.id,title:legacy.title}]}}));
    await page.reload();
    await page.locator('#output-body [data-action=file]').click();
    await page.getByText('旧版文本成果', {exact:true}).waitFor();
    assert.equal(await page.locator('#output-body .output-list').count(),0);
    const chatBeforeBack = await page.locator('#chat-body').innerText();
    await page.getByRole('button',{name:'返回成果列表',exact:true}).click();
    assert.equal(await page.locator('#output-body .output-detail').count(),0);
    assert.equal(await page.locator('#output-body [data-action=file]').evaluate(e=>e===document.activeElement),true);
    assert.equal(await page.locator('#chat-body').innerText(),chatBeforeBack);
    await page.locator('#output-body [data-action=file]').press('Enter');
    await page.getByText('旧版文本成果', {exact:true}).waitFor();
    assert.equal(await page.locator('#studio-tools a').count(), 0);
    assert.equal(await page.locator('#output-body a[href$="/download"]').count(), 0);
    assert.match(await page.locator('#output-body').innerText(), /保留的历史正文/);
    const material = await getJson(port, `/api/projects/${saved.id}/papers/${saved.papers[0].id}`);
    const citation = {id:'cite-check', title:'A_very_long_paper_title_that_must_stay_on_one_line_even_in_a_narrow_column', paper_id:material.id, paper_version_id:material.version_id, page:1, rect:null, quote:'This raw excerpt must not fill the chat.'};
    legacy.versions[0].citations = [citation];
    let progress = {id:'progress-check',status:'running',events:[{seq:1,status:'tool_start',message:'正在阅读 · 展示约定',step_id:'read'}], plan:[{id:'read',title:'读取相关材料',status:'in_progress'},{id:'compare',title:'核对展示约定',status:'pending'},{id:'answer',title:'整理研究结论',status:'pending'}], citations:[citation], tools:[], files:[], artifact_id:null};
    const view = JSON.parse(await page.evaluate(() => localStorage.getItem('methodatlas-view')));
    let historical = [];
    const progressProject = () => ({...saved, artifacts:[{id:legacy.id,title:legacy.title}], conversations:[{id:view.conversationId,title:'任务过程检查',reads:[],messages:[...historical,{role:'user',text:'核对材料并整理结论',task:progress,task_id:progress.id}, ...(progress.status === 'succeeded' ? [{role:'assistant',text:`已完成核对。[cite:cite-check] [下载 DOCX](/api/projects/${saved.id}/artifacts/legacy/versions/legacy-v1/download)`,task:progress}] : [])]}]});
    await page.route(`**/api/projects/${saved.id}`, route => route.fulfill({json:progressProject()}));
    await page.route(`**/api/projects/${saved.id}/tasks/progress-check`, route => route.fulfill({json:progress}));
    await page.route(`**/api/projects/${saved.id}/citations/cite-check`, route => route.fulfill({json:citation}));
    await page.reload();
    await page.locator('#output-body [data-action=file]').click();
    await page.locator('.working .research-plan').waitFor();
    assert.equal(await page.locator('[data-action=resume],[data-action=redirect]').count(),0);
    assert.equal(await page.locator('#output-body [data-action=task]').count(),0);
    assert.equal(await page.locator('.working .plan-step[data-state=active]').count(), 1);
    assert.equal(await page.locator('.working .current-action').count(), 1);
    assert.equal(await page.locator('.working .step-details[open]').count(), 0);
    assert.equal(await page.locator('#chat-body .evidence-link').count(), 0);
    assert.doesNotMatch(await page.locator('#chat-input').getAttribute('placeholder'), /阅读|read_material/);
    await page.locator('.working .step-details>summary').click();
    await page.waitForTimeout(1150);
    assert.equal(await page.locator('.working .step-details[open]').count(), 1, 'polling must preserve the open step');
    assert.equal(await page.locator('#chat-input').isDisabled(),false,'research must leave the composer enabled');
    progress = {...progress, events:[...progress.events,{seq:2,status:'connection_retry',message:'模型连接不稳定，正在自动重试…'}]};
    await page.getByRole('status').filter({hasText:'模型连接不稳定，正在自动重试'}).waitFor();
    await page.locator('#chat-input').fill('研究中正在输入的追问');
    progress = {...progress, plan:[{id:'read',title:'读取相关材料',status:'completed',summary:'已读取笔记中的展示约定。'},{id:'compare',title:'核对展示约定',status:'in_progress'},progress.plan[2]], events:[...progress.events,{seq:2,status:'tool_done',message:'已阅读 · 展示约定',step_id:'read'},{seq:3,status:'tool_start',message:'正在核对 · 展示约定',step_id:'compare'}]};
    await page.locator('.working .plan-step[data-state=completed]').waitFor();
    assert.equal(await page.locator('#chat-input').inputValue(),'研究中正在输入的追问');
    assert.equal(await page.locator('#chat-input').evaluate(node => node === document.activeElement),true);
    assert.equal(await page.locator('.working .step-details[open]').count(), 1, 'explicitly opened step stays open on completion');
    assert.equal(await page.locator('.working .current-action').count(), 1);
    assert.match(await page.locator('.working .plan-step[data-state=completed]').innerText(), /已读取笔记/);
    await page.screenshot({path:path.join(screenshots,'plan-running.png')});
    progress = {...progress,status:'succeeded',files:[{artifact_id:'legacy',version_id:'legacy-v1',title:'旧版综述',kind:'docx',version_no:1,downloadable:true}],plan:[progress.plan[0],{id:'compare',title:'核对展示约定',status:'completed',summary:'已确认颜色来自用户笔记。'},{id:'answer',title:'整理研究结论',status:'completed',summary:'已整理回答并保留原文链接。'}]};
    await page.locator('.answer-text').waitFor();
    assert.equal(await page.locator('#chat-body a[href$="/download"]').count(),0);
    assert.equal(await page.locator('#chat-body [data-action=file]').count(),1);
    assert.equal(await page.locator('#output-body [data-action=task]').count(),0);
    assert.equal(await page.locator('.execution-record[open]').count(), 1, 'explicitly opened child keeps its record accessible');
    assert.equal(await page.locator('#chat-body summary').filter({hasText:'原文依据'}).count(), 0);
    assert.equal(await page.locator('.message.agent').evaluate(node => !!(node.querySelector('.execution-record').compareDocumentPosition(node.querySelector('.answer-text')) & Node.DOCUMENT_POSITION_FOLLOWING)), true);
    assert.ok((await page.locator('.citation-inline').boundingBox()).height < 28);
    assert.equal(await page.locator('.artifact-sources[open]').count(),0);
    await page.locator('.artifact-sources>summary').click();
    assert.ok((await page.locator('#output-body .evidence-link').boundingBox()).height < 30);
    await page.locator('[data-action=history]').click();
    await page.locator('#conversation-menu').waitFor();
    await page.locator('.citation-inline').click();
    await page.locator('.paper-drawer').waitFor();
    assert.equal(await page.locator('#conversation-menu').count(),0,'history must not cover a citation destination');
    assert.equal(await page.locator('[data-action=history]').getAttribute('aria-expanded'),'false');
    assert.match(await page.locator('.paper-drawer').innerText(), /青色代表感知/);
    assert.equal(await page.locator('.plan-step[data-state=completed]').count(), 3);
    await page.screenshot({path:path.join(screenshots,'plan-completed-expanded.png')});
    progress = {...progress,status:'interrupted',blocked_reason:'验证中断',plan:[progress.plan[0],{id:'compare',title:'核对展示约定',status:'in_progress'}]};
    await page.reload();
    await page.getByRole('status').filter({hasText:'已中断：验证中断'}).waitFor();
    assert.equal(await page.locator('.message.agent a[href$="/download"]').count(),0);
    assert.equal(await page.locator('.message.agent [data-action=file]').count(),1);
    await page.locator('.execution-record>summary').click();
    assert.equal(await page.locator('.plan-step[data-state=active]').count(), 0);
    assert.match(await page.locator('.plan-step[data-state=interrupted]').innerText(), /已中断/);
    progress = {...progress,status:'running'};
    historical = ['old-a','old-b'].map(id => ({role:'user',text:id,task_id:id,task:{...progress,id,status:'succeeded',tools:[{name:'locate',status:'succeeded'}]}}));
    let repeatedLocations = 0;
    page.on('request', request => { if (request.url().endsWith('/citations/cite-check')) repeatedLocations++; });
    await page.reload();
    await page.locator('.working').waitFor();
    await page.waitForTimeout(2200);
    assert.equal(repeatedLocations,0,'refresh must not replay historical PDF navigation');
    legacy.versions[0].kind = 'html';
    legacy.versions[0].materials = legacy.versions[0].citations.map(c => ({paper_id:c.paper_id,paper_version_id:c.paper_version_id}));
    legacy.versions[0].body = `<html><head><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'nonce-check'"></head><body><h1>网页成果</h1><section><h2>原文依据</h2><button data-citation="cite-check">展示约定</button></section><script nonce="check">document.addEventListener('click',e=>{if(e.target.dataset.citation)parent.postMessage({type:'methodatlas-citation',id:e.target.dataset.citation},'*')})</script></body></html>`;
    await page.locator('#output-body [data-action=file]').click();
    const preview = page.frameLocator('#html-preview');
    await preview.getByRole('heading',{name:'网页成果'}).waitFor();
    const frameBox = await page.locator('#html-preview').boundingBox(), bodyBox = await page.locator('#output-body').boundingBox();
    assert.ok(Math.abs(frameBox.width-bodyBox.width)<2 && Math.abs(frameBox.height-bodyBox.height)<2,'HTML fills Studio below its header');
    assert.equal(await page.locator('#output-body .evidence-list').count(),0);
    assert.equal(await preview.locator('details[open]').count(),0);
    await preview.getByText('引用的来源',{exact:true}).click();
    await preview.getByRole('button',{name:'展示约定'}).click();
    await page.locator('.paper-drawer').waitFor();
    assert.match(await page.locator('.paper-drawer').innerText(),/青色代表感知/);
    assert.deepEqual(errors, []);
    console.log('PASS: real project creation, refreshed counts, search/sort, saved grid/list view, mobile home, reduced motion, served assets, and shortcuts that preserve drafts without submitting.');
    console.log('PASS: plan progression, collapsed details, polling state, completion/interruption, no chat evidence list, and single-line working citations.');
    console.log('PASS: three columns, pasted material, stale-task isolation, refresh, missing-key failure, and legacy text without invalid downloads.');
  } finally {
    await browser.close();
    server.kill();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
