import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { mkdir } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { resolve } from 'node:path';
import React from 'react';
import { renderToString } from 'react-dom/server';

await mkdir('.check-data', {recursive:true});
const output = resolve('.check-data/writing-editor.mjs');
await build({entryPoints:['prototype/writing-editor.jsx'],outfile:output,bundle:true,platform:'node',format:'esm',packages:'external'});
const { makeEditor, proposalEditor, resolveProposal, Editor, nodeText, normalizedDocument } = await import(pathToFileURL(output));
const before = [{id:'paragraph',type:'p',children:[{text:'原文 42。'}]}];
const after = [{id:'paragraph',type:'p',children:[{text:'修订 42。'}]}];
const preview = proposalEditor(before, after);
const restored = makeEditor(JSON.parse(JSON.stringify(preview.children)));
assert.match(renderToString(React.createElement(Editor,{editor:restored,readOnly:true})), /<del/);
assert.match(renderToString(React.createElement(Editor,{editor:restored,readOnly:true})), /<ins/);
assert.equal(resolveProposal(restored, true).map(nodeText).join('\n'), '修订 42。');
assert.equal(resolveProposal(restored, true).map(nodeText).join('\n'), '修订 42。');
assert.equal(resolveProposal(proposalEditor(before, after), false).map(nodeText).join('\n'), '原文 42。');
const inserted = [...after, {id:'new',type:'h2',children:[{text:'新章节'}]}];
assert.equal(resolveProposal(proposalEditor(before, inserted), true).map(nodeText).join('\n'), '修订 42。\n新章节');
assert.equal(resolveProposal(proposalEditor(before, inserted), false).map(nodeText).join('\n'), '原文 42。');
assert.equal(normalizedDocument(resolveProposal(proposalEditor(before, inserted), true)), normalizedDocument(inserted));
assert.equal(normalizedDocument(resolveProposal(proposalEditor(before, inserted), false)), normalizedDocument(before));
const cited = [{id:'cited',type:'p',children:[{text:'事实。'},{type:'citation',citation_id:'cite_real',children:[{text:''}]}]}, ...before];
const revised = [cited[0], ...after];
for (const accept of [true, false]) assert.equal(normalizedDocument(resolveProposal(proposalEditor(cited, revised), accept)), normalizedDocument(accept ? revised : cited));
const wrongCitation = structuredClone(revised); wrongCitation[0].children[1].citation_id = 'cite_other';
assert.notEqual(normalizedDocument(revised), normalizedDocument(wrongCitation));
console.log('PASS: pinned Plate suggestions, JSON recovery, insert/delete display, whole accept/reject and repeated decision');
const {selectionSnapshot} = await import(pathToFileURL(output));
const structured = [{id:'h',type:'h2',children:[{text:'前😀标题'}]}, {id:'l',type:'ul',children:[{type:'li',children:[{text:'条目'},{type:'citation',citation_id:'c',children:[{text:''}]},{text:'后文'}]}]}];
const range = {anchor:{path:[1,0,2],offset:1},focus:{path:[0,0],offset:3}};
assert.equal(selectionSnapshot(structured,range).text,'标题\n条目\n[引用]\n后');
assert.equal(selectionSnapshot(structured,range).editable,true);
const structuredAfter = structuredClone(structured);structuredAfter[0].children[0].text='前😀新标题';structuredAfter[1].children[0].children[0].text='新条目';
for(const accept of [true,false])assert.equal(normalizedDocument(resolveProposal(proposalEditor(structured,structuredAfter),accept)),normalizedDocument(accept?structuredAfter:structured));
console.log('PASS: selection snapshot and structured/citation review round-trip');

const {citationNumbers} = await import(pathToFileURL(output));
const refs = [{id:'a',paper_id:'paper-a'},{id:'b',paper_id:'paper-b'},{id:'a-page2',paper_id:'paper-a'}];
assert.deepEqual(citationNumbers(refs), {a:1,b:2,'a-page2':1});
const reordered = makeEditor([{type:'p',children:[{text:''},...['b','a','b'].map(citation_id=>({type:'citation',citation_id,children:[{text:''}]}))]}]);
const markup = renderToString(React.createElement(Editor,{editor:reordered,citations:refs,readOnly:true}));
assert.deepEqual([...markup.matchAll(/aria-label="引用 (\d+)"/g)].map(m=>m[1]),['2','1','2']);
console.log('PASS: shared reference numbers across papers, repeated citations and insertion order');
