// Run against saved real research: node prototype/check-methods.cjs URL PROJECT_ID
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { chromium } = require('playwright');

(async () => {
  const [base, project] = process.argv.slice(2);
  assert.ok(base && project, 'Provide the workbench URL and validation project ID');
  const get = async path => { const response = await fetch(base + path); assert.ok(response.ok); return response.json(); };
  const projectUrl = `/api/projects/${project}`;
  const state = await get(projectUrl);
  const artifacts = await Promise.all(state.artifacts.map(a => get(`${projectUrl}/artifacts/${a.id}`)));
  const map = artifacts.find(a => a.versions.at(-1).payload.research?.view === 'methods');
  const timeline = artifacts.find(a => a.versions.at(-1).payload.research?.view === 'evolution');
  assert.ok(map && timeline, 'Both research views must have been generated by the real Agent');
  assert.ok(map.versions.length >= 2, 'Generate a real conversational revision before this check');
  const browser = await chromium.launch({channel:'chromium',headless:true});
  try {
    const page = await browser.newPage({viewport:{width:1500,height:1000}});
    page.setDefaultTimeout(20000);
    const errors = []; page.on('pageerror', e => errors.push(e.message));
    await page.goto(base);
    await page.locator(`[data-action="open-project"][data-id="${project}"]`).click();
    await page.locator('#chat-input').waitFor();
    const researchConversation = state.conversations.find(c => c.messages.some(m => m.task_id === map.versions[0].task_id));
    assert.ok(researchConversation);
    await page.locator('[data-action="history"]').click();
    await page.locator(`[data-action="conversation"][data-id="${researchConversation.id}"]`).click();
    await page.locator('#conversation-menu').waitFor({state:'detached'});
    await page.locator('.output-list').waitFor();
    const open = async a => {
      if (await page.locator('[data-action="artifact-list"]:visible').count()) await page.locator('[data-action="artifact-list"]').click();
      await page.locator(`.output-list [data-id="${a.id}"]`).click();
      await page.frameLocator('#html-preview').locator('.research-view').waitFor();
      return page.frameLocator('#html-preview');
    };
    let frame = await open(map);
    for (const node of await frame.locator('[data-method]').all()) {
      for (const relation of (await node.getAttribute('data-related')).split(' ')) {
        const relatedPaper = frame.locator(`.research-papers [data-related="${relation}"]`);
        await node.hover(); assert.ok((await relatedPaper.getAttribute('class')).includes('research-linked'));
        await relatedPaper.hover(); assert.ok((await node.getAttribute('class')).includes('research-linked'));
      }
    }
    const method = frame.locator('[data-method]').first();
    const key = (await method.getAttribute('data-related')).split(' ')[0];
    const paper = frame.locator(`.research-papers [data-related="${key}"]`);
    await method.hover(); assert.ok((await paper.getAttribute('class')).includes('research-linked'));
    assert.equal(await frame.locator('[data-method].research-linked').count(),1);
    await paper.hover(); assert.ok((await method.getAttribute('class')).includes('research-linked'));
    await method.focus(); await method.press('Enter');
    assert.equal(await frame.locator('[data-detail]:visible').count(),1);
    assert.equal(await method.getAttribute('aria-expanded'),'true');
    const citationId = await paper.getAttribute('data-citation');
    const originalCitation = map.versions.at(-1).citations.find(c => c.id === citationId);
    await paper.click();
    assert.equal(await frame.locator('.reading-quote:popover-open').textContent(),originalCitation.quote);
    await paper.press('Escape');
    const paperNumber=Number((await paper.textContent()).match(/\[(\d+)\]/)[1]);
    await frame.locator('[data-source-open]').nth(paperNumber-1).click();
    await page.locator(`#paper-detail .reader-shell[data-version="${originalCitation.paper_version_id}"]`).waitFor();
    await page.locator('#paper-detail .responsive-paper .reader-evidence').first().waitFor({state:'visible'});
    assert.equal(await page.locator('#paper-detail .original-reader').count(),0);
    await frame.locator('[data-detail]:visible [data-close-detail]').click();
    assert.equal(await frame.locator('[data-detail]:visible').count(),0);
    await page.screenshot({path:'output/playwright/issue50-methods-interaction.png',fullPage:true});
    frame = await open(timeline);
    for (const stageRow of await frame.locator('.research-timeline .research-stage').all()) {
      await stageRow.locator('[data-method]').click(); assert.equal(await frame.locator('[data-detail]:visible').count(),1);
      await frame.locator('[data-detail]:visible [data-close-detail]').click();
      await stageRow.locator('.research-paper').first().click(); assert.equal(await frame.locator('[data-detail]:visible').count(),0);
    }
    const stage = frame.locator('[data-method]').first();
    await stage.click(); assert.equal(await frame.locator('[data-detail]:visible').count(),1);
    await frame.locator('[data-detail]:visible [data-close-detail]').click();
    const representative = frame.locator('.research-timeline .research-paper').first();
    await representative.click(); assert.equal(await frame.locator('[data-detail]:visible').count(),0);
    await page.screenshot({path:'output/playwright/issue50-timeline-interaction.png',fullPage:true});
    frame = await open(map);
    // A citation request already in flight cannot update the reader after a version switch.
    await page.locator('[data-action="close-paper"]').click();
    let release, requested;
    const held = new Promise(resolve => { release = resolve; });
    const started = new Promise(resolve => { requested = resolve; });
    await page.route('**/citations/*', async route => { requested(); await held; await route.continue(); });
    await frame.locator('[data-source-open]').nth(paperNumber-1).click(); await started;
    await page.locator('#version-select').selectOption(map.versions[0].id);
    release(); await page.waitForTimeout(500);
    assert.equal(await page.locator('#paper-detail .paper-drawer').count(),0);
    await page.unroute('**/citations/*');
    // Wrong source window and stale preview windows cannot send citation messages.
    await page.evaluate(id => window.postMessage({type:'methodatlas-citation',id},'*'), originalCitation.id);
    await page.waitForTimeout(100); assert.equal(await page.locator('#paper-detail .paper-drawer').count(),0);
    const before = await get(`${projectUrl}/artifacts/${map.id}`);
    await page.locator('[data-action="restore-artifact"]').click();
    await page.locator('#version-select option').filter({hasText:new RegExp(`^v${before.versions.length+1}$`)}).waitFor({state:'attached'});
    const restored = await get(`${projectUrl}/artifacts/${map.id}`);
    assert.equal(restored.versions.length,before.versions.length+1);
    assert.equal(restored.versions.at(-1).body,restored.versions[0].body);
    assert.equal(restored.versions.at(-2).body,before.versions.at(-1).body);
    await page.reload(); await page.locator('#chat-input').waitFor();
    frame = await open(restored);
    assert.equal(await page.locator('#version-select').inputValue(),restored.versions.at(-1).id);
    await page.locator('#version-select').selectOption(restored.versions[0].id);
    await frame.locator('[data-source-open]').nth(paperNumber-1).click();
    await page.locator(`#paper-detail .reader-shell[data-version="${originalCitation.paper_version_id}"]`).waitFor();
    // Saved files must be actual bytes; citations must map to the exact saved paper version.
    for (const artifact of [restored,timeline]) for (const version of artifact.versions) {
      const file = await fetch(`${base}${projectUrl}/artifacts/${artifact.id}/versions/${version.id}/download`);
      assert.ok(file.ok); assert.match(await file.text(),/research-view/);
      for (const cite of version.citations) {
        const actual = await get(`${projectUrl}/citations/${cite.id}`);
        assert.equal(actual.paper_version_id,cite.paper_version_id);
        const paperVersion = await get(`${projectUrl}/papers/${cite.paper_id}?version_id=${cite.paper_version_id}`);
        const sourcePage = paperVersion.pages.find(p => p.page === cite.page);
        assert.equal(Array.from(sourcePage.text).slice(cite.start,cite.end).join(''),cite.quote);
      }
    }
    await page.locator('[data-action="artifact-list"]').click();
    assert.equal(await page.locator('#html-preview').count(),0);
    // A delayed restore response must not override a later navigation to a different artifact.
    await open(restored);
    await page.locator('#version-select').selectOption(restored.versions[0].id);
    let releaseRestore, restoreStarted, releaseNavigation, navigationStarted;
    const restoreHold = new Promise(resolve => { releaseRestore = resolve; });
    const restoring = new Promise(resolve => { restoreStarted = resolve; });
    const navigationHold = new Promise(resolve => { releaseNavigation = resolve; });
    const navigating = new Promise(resolve => { navigationStarted = resolve; });
    await page.route('**/artifacts/*/restore',async route => { const result=await route.fetch(); restoreStarted(); await restoreHold; await route.fulfill({response:result}); });
    await page.route(`**/artifacts/${timeline.id}`,async route => { navigationStarted(); await navigationHold; await route.continue(); });
    await page.locator('[data-action="restore-artifact"]').click(); await restoring;
    await page.locator(`.message [data-action="file"][data-id="${timeline.id}"]`).first().click(); await navigating;
    releaseRestore(); await page.waitForTimeout(100); releaseNavigation();
    await page.frameLocator('#html-preview').locator('.research-timeline').waitFor();
    await page.unroute('**/artifacts/*/restore'); await page.unroute(`**/artifacts/${timeline.id}`);
    assert.deepEqual(errors,[]);
    fs.writeFileSync('output/playwright/issue50-browser-result.json',JSON.stringify({project,map:map.id,timeline:timeline.id,restored:restored.versions.at(-1).id,errors},null,2));
    console.log('PASS real methods/papers hover+keyboard, stages independent clicks, exact citations, stale preview, safe restore, refresh and downloads');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode=1; });
